"""Permutations and combinations generated by backtracking."""
def permutations(items: list) -> list[tuple]:
    result = []
    used = [False] * len(items)

    def backtrack(current: list) -> None:
        if len(current) == len(items):
            result.append(tuple(current))
            return
        for i, item in enumerate(items):
            if not used[i]:
                used[i] = True
                current.append(item)
                backtrack(current)
                current.pop()
                used[i] = False

    backtrack([])
    return result


def combinations(items: list, k: int) -> list[tuple]:
    result = []

    def backtrack(start: int, current: list) -> None:
        if len(current) == k:
            result.append(tuple(current))
            return
        for i in range(start, len(items)):
            current.append(items[i])
            backtrack(i + 1, current)
            current.pop()

    backtrack(0, [])
    return result


if __name__ == "__main__":
    assert permutations([1, 2, 3]) == [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
    assert combinations([1, 2, 3, 4], 2) == [(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
    print("permutation generation ok")
